version: "3"
services:
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=socialApp
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d