// Global Variables
@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@postId = 1
@commentId = 3
@likeId = 1
@fullName = kofta
@email = kofta@kofta.net
@password = 1234


// Posts

// Create a post
POST  http://{{host}}/posts
Content-Type: {{contentType}}

{
    "content": "hello"
}

###

// Get all posts
GET http://{{host}}/posts

###

// Edit a post
PUT http://{{host}}/posts?postId={{postId}}
Content-Type: {{contentType}}

{
    "content": "yo"
}

###

// Delete a post
DELETE http://{{host}}/posts?postId={{postId}}

###

// Comments

// Create a comment
POST http://{{host}}/comments?postId={{postId}}
Content-Type: {{contentType}}

{
    "content": "comment"
}

// Get all comments for a post
###
GET http://{{host}}/comments?postId={{postId}}

###

// Edit a comment
PUT http://{{host}}/comments?commentId={{commentId}}
Content-Type: {{contentType}}

{
    "content": "comment2"
}

###

// Delete a comment
DELETE http://{{host}}/comments?commentId={{commentId}}

###

// Posts likes

// Get likes for a post
GET http://{{host}}/likes?postId={{postId}}

###

// Like a post
POST http://{{host}}/likes?postId={{postId}}

###

// Comment likes

// Get likes for a comment
GET http://{{host}}/likes?commentId={{commentId}}

###

// Like a comment
POST http://{{host}}/likes?commentId={{commentId}}

###

// Unlike posts or comments
DELETE http://{{host}}/likes?likeId={{likeId}}

###

// Auth

// Signup a user
POST http://{{host}}/signup
Content-Type: {{contentType}}

{
    "fullName": "{{fullName}}",
    "email": "{{email}}",
    "password": "{{password}}"
}

###

// Login a user
POST http://{{host}}/login
Content-Type: {{contentType}}

{
    "email": "{{email}}",
    "password": "{{password}}"
}


